name: Deploy site

on:
  push:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      
      - name: Build site
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ matrix.branch == 'main' && '' || 'dev' }}
